server: { port: 8082 }
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:mem:booking;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
  sql.init.mode: always
auth.jwt.secret: "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCD"
management.endpoints.web.exposure.include: health,info,prometheus
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hotel:
  client:
    connect-timeout-ms: 800
    read-timeout-ms: 1500
    retries: 3
    backoff-ms: 200