name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build & Verify
        env:
          AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET || 'dev-secret-0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCD' }}
          SPRING_PROFILES_ACTIVE: dev-test
        run: mvn -V -q -B -Pdev-test verify
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
            **/target/site/jacoco/**
